jetcache:
  # 控制台输出统计数据，统计间隔（单位分钟），0表示不统计
  statIntervalMinutes: 1
  # 是否加入缓存key前缀
  areaInCacheName: false
  local:
    default:
      # 缓存类型。linkedhashmap、caffeine为当前支持的本地缓存类型
      type: linkedhashmap
      # Key的转换器
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      # 缓存类型。tair、redis为当前支持的远程缓存
      type: redis
      keyConvertor: fastjson
      # 采用Java序列化存储
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
      password: 123456